# Generated by Django 4.0 on 2022-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_registraton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=100)),
                ('Role', models.CharField(max_length=50)),
                ('FromTime', models.IntegerField()),
                ('ToTime', models.IntegerField()),
            ],
        ),
    ]
